import { HOURLY_RATE_HUF } from "@/lib/booking/constants";

export const booking = {
  title: "Foglalás",
  lead: "Válassza ki az időpontot és pályát, majd adja meg a játékosok számát és nevét.",
  loadError: {
    empty: "Jelenleg nincs elérhető pálya. Próbálja később.",
  },
  loginRequired: {
    title: "Bejelentkezés szükséges",
    body: "A foglaláshoz jelentkezzen be, vagy hozzon létre fiókot.",
    login: "Bejelentkezés",
    register: "Regisztráció",
  },
  steps: {
    day: {
      title: "Nap kiválasztása",
      shortTitle: "Nap",
      lead: "Válasszon napot a foglaláshoz.",
      lead2: "",
      weekdays: ["H", "K", "Sze", "Cs", "P", "Szo", "V"],
      available: "Szabad",
    },
    time: {
      title: "Idősáv",
      shortTitle: "Idő",
      lead: "Válasszon idősávot a foglaláshoz.",
      lead2: "A nyitvatartási időn belül a minimális foglalási idő 1 óra. 20:00 órai kezdésnél a maximális foglalási idő 1 óra.",
      hintStart: "Válassza ki a kezdés idejét.",
      hintEnd: "Válassza ki a befejezés idejét (legalább 1 órával később).",
      selected: "Kiválasztott sáv",
      past: "Elmúlt",
      available: "Választható",
      fullyBooked: "Teljesen foglalt",
    },
    court: {
      title: "Pályaválasztás",
      shortTitle: "Pálya",
      lead: "Válasszon pályát a foglaláshoz.",
      lead2: "",
      available: "Szabad",
      busy: "Foglalt",
      loading: "Foglaltság betöltése…",
    },
    type: {
      title: "Részletek",
      shortTitle: "Típus",
      lead: "Válassza ki a foglalás típusát, majd adja meg a játékosok számát és nevét.",
      lead2: "",
      seasonPass: {
        title: "Szezonbérletem van",
        body: "Bérletes pályahasználat — nincs óránkénti díj a foglaláskor.",
      },
      oneTime: {
        title: "Egyedi foglalás",
        body: `Pályabérleti díj: ${HOURLY_RATE_HUF.toLocaleString("hu-HU")} Ft / óra. Fizetés módja később egyeztetendő.`,
      },
      players: {
        title: "Játékosok száma",
        two: "2 fő",
        four: "4 fő",
        hint: "A díj páros és négyes játéknál is azonos.",
      },
      names: {
        title: "Játékosok nevei",
        hint: "Az Ön neve a profilból jön; adja meg a többi játékos nevét.",
        bookerLabel: "Ön (profil)",
        bookerFallback: "Profil név nincs megadva",
        guestLabel: "Játékos {n}",
        guestPlaceholder: "Teljes név",
      },
    },
    confirm: {
      title: "Összegzés",
      shortTitle: "Összegzés",
      lead: "Ellenőrizze a foglalást, majd erősítse meg.",
      lead2: "",
      court: "Pálya",
      date: "Nap",
      time: "Idő",
      type: "Típus",
      players: "Játékosok",
      playerNames: "Nevek",
      price: "Díj",
      priceFree: "Bérletes — 0 Ft",
      paymentNote: "Az egyedi díj fizetése később kerül kialakításra.",
      submit: "Foglalás megerősítése",
      submitting: "Foglalás…",
      success: "Sikeres foglalás!",
      successBody: "A kiválasztott pálya és időpont rögzítve.",
      another: "Új foglalás",
      home: "Vissza a kezdőlapra",
      help: "Segítségkérés",
    },
  },
  help: {
    title: "Problémába ütközött?",
    body: "Amennyiben kérdése, problémája van a foglalással, írjon nekünk üzenetet.",
    cta: "Kapcsolatfelvétel",
    href: "/contact?help=booking#form-heading",
  },
  nav: {
    back: "Vissza",
    next: "Tovább",
  },
  errors: {
    auth: "A foglaláshoz be kell jelentkeznie.",
    overlap: "Ez az idősáv már foglalt. Válasszon másik időt.",
    generic: "Nem sikerült a foglalás. Próbálja újra.",
    invalidRange: "Az idősáv legalább 1 óra legyen, :00 vagy :30 határokkal.",
    guestNames: "Adja meg minden társ játékos nevét.",
  },
} as const;

export type BookingContent = typeof booking;
