export const profile = {
  title: "Profil",
  support: "Kezelje személyes adatait, profilképét és biztonsági beállításait.",
  emailLabel: "E-mail cím",
  emailBadge: "Aktivált fiókazonosító",
  tabs: {
    details: "Személyes adatok",
    security: "Biztonság & Fiók",
    pass: "Bérletem",
  },
  pass: {
    active: {
      badge: "Érvényes bérlet",
      title: "{year}-os Szezonbérlet",
      description: "Az Ön szezonbérlete aktív erre a szezonra. Korlátlan számú pályafoglalásra jogosult az adott évben.",
      detailsTitle: "Bérlet adatai",
      seasonLabel: "Szezon",
      seasonValue: "{year}. évi szezon",
      registeredEmail: "Regisztrált email",
      statusLabel: "Státusz",
      statusValue: "Aktív",
      grantedAtLabel: "Rögzítve",
      bookButton: "Pályafoglalás indítása",
    },
    expired: {
      badge: "Nincs érvényes bérlet",
      title: "Nincs bérlete a(z) {year}-os szezonra",
      description: "Ön rendelkezik korábbi szezonbérlettel, de az aktuális évre még nem aktiváltak bérletet az Ön számára.",
      contactLead: "Új szezonbérlet igényléséhez kérjük, vegye fel a kapcsolatot a klub vezetőségével.",
      contactButton: "Kapcsolatfelvétel",
      pricesButton: "Árak megtekintése",
    },
    empty: {
      title: "Jelenleg nincs aktív szezonbérlete",
      description: "A szezonbérlettel rendelkező tagok korlátlanul és díjmentesen foglalhatnak pályát a megadott szezonban. Szezonbérletet a klub vezetősége tud rögzíteni az Ön profiljához.",
      contactButton: "Kapcsolatfelvétel a vezetőséggel",
      pricesButton: "Díjszabás megtekintése",
    },
    history: {
      title: "Bérlet előzmények",
      lead: "Az Ön korábbi és jelenlegi szezonbérletei a klubban.",
      seasonColumn: "Szezon",
      statusColumn: "Státusz",
      dateColumn: "Rögzítve",
      activeBadge: "Érvényes",
      expiredBadge: "Lejárt",
      futureBadge: "Jövőbeli",
    },
  },
  avatar: {
    title: "Profilkép",
    support: "Töltsön fel egy képet magáról (JPG, PNG, WEBP, max 2 MB).",
    uploadButton: "Fotó feltöltése",
    uploadingButton: "Feltöltés…",
    removeButton: "Fotó eltávolítása",
    removingButton: "Eltávolítás…",
    badgeLabel: "Profilkép",
  },
  sections: {
    details: {
      title: "Személyes információk",
      support: "Itt frissítheti a rendszerben megjelenő nevét és elérhetőségét.",
      submit: "Módosítások mentése",
      submitting: "Mentés folyamatban…",
    },
    password: {
      title: "Jelszó módosítása",
      support: "Változtassa meg jelszavát fiókja biztonságának megőrzése érdekében.",
      submit: "Jelszó frissítése",
      submitting: "Frissítés…",
    },
    delete: {
      badge: "Veszélyzóna",
      title: "Fiók végleges törlése",
      support:
        "A fiók törlése azonnali és visszafordíthatatlan művelet. Minden aktív bérlete és foglalási előzménye véglegesen törlésre kerül.",
      confirmLabel: "Megértettem a következményeket, véglegesen törlöm a fiókomat.",
      submit: "Fiók törlése",
      submitting: "Törlés folyamatban…",
    },
  },
  fields: {
    fullName: { label: "Teljes név" },
    phone: { label: "Telefonszám", placeholder: "+36 (30) 123-4567" },
    currentPassword: { label: "Jelenlegi jelszó" },
    password: { label: "Új jelszó" },
    passwordConfirm: { label: "Új jelszó megerősítése" },
    deletePassword: { label: "Jelszó a törlés megerősítéséhez" },
  },
  notices: {
    accountDeleted: "A fiók törölve lett.",
  },
} as const;

export type ProfileContent = typeof profile;
